# Generated by Django 2.2 on 2019-05-09 15:47

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [('user', '0001_initial')]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ('name', models.CharField(max_length=250)),
                ('secret', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                (
                    'creator',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='passport_created_by',
                        to='user.UserProfile',
                    ),
                ),
            ],
            options={'verbose_name': 'Passport', 'ordering': ('pk',)},
        )
    ]
