# Generated by Django 2.2 on 2019-04-07 19:22

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ('role', models.CharField(choices=[('U', 'user'), ('A', 'admin')], default='U', max_length=1)),
                ('is_system', models.BooleanField(default=False)),
                ('login', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={'verbose_name': 'User Profile', 'ordering': ('pk',)},
        ),
        migrations.CreateModel(
            name='SystemUserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.TextField(blank=True, null=True)),
                (
                    'profile',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='system_user_data',
                        to='user.UserProfile',
                    ),
                ),
            ],
        ),
    ]
