# Generated by Django 2.2.1 on 2019-05-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('user', '0001_initial')]

    operations = [
        migrations.AddIndex(
            model_name='userprofile', index=models.Index(fields=['is_system'], name='user_userpr_is_syst_3547ae_idx')
        )
    ]
