# Generated by Django 2.2 on 2019-04-08 19:56

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [('user', '0001_initial')]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    'post_type',
                    models.CharField(
                        choices=[('text', 'text'), ('video', 'video'), ('image', 'image')],
                        default='text',
                        max_length=10,
                    ),
                ),
                ('text', models.TextField(default='')),
                ('youtube_link', models.TextField(null=True)),
                ('image', models.ImageField(max_length=254, upload_to='photos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                (
                    'creator',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='user.UserProfile'
                    ),
                ),
            ],
            options={'verbose_name': 'Wall Post', 'ordering': ('pk',)},
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile')),
                (
                    'post',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='likes_counter', to='post.Post'
                    ),
                ),
            ],
        ),
    ]
