# Generated by Django 2.2 on 2019-05-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('post', '0001_initial')]

    operations = [
        migrations.AlterModelOptions(name='post', options={'ordering': ('-created_at',), 'verbose_name': 'Wall Post'}),
        migrations.AlterField(
            model_name='post', name='image', field=models.ImageField(max_length=254, null=True, upload_to='photos')
        ),
        migrations.AlterField(
            model_name='post', name='text', field=models.TextField(blank=True, default='', null=True)
        ),
        migrations.AlterField(model_name='post', name='youtube_link', field=models.TextField(blank=True, null=True)),
    ]
