# Generated by Django 2.2.1 on 2019-05-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('post', '0002_auto_20190509_1547')]

    operations = [
        migrations.AddIndex(
            model_name='like', index=models.Index(fields=['post', 'creator'], name='post_like_post_id_ad9b0d_idx')
        )
    ]
